<template>
    <div class="content">
        <div class="content-ten">
            <p>●<br>もの</p>
        </div>
        <p class="content-name"><strong>ツバキ</strong></p>
        <p>CAMELLIA JAPONICA</p>
        <p>ツバキ科ツバキ属</p>
        <p class="content_editdate">by 国立国会図書館 2018年8月24日作成（8月29日最終更新）</p>
    </div>
</template>

<script>
</script>

<style scoped>
.content{
    background-color: #870808;
    width: 100vw;
    position: relative;
    left: 50%;
    transform: translateX(-50%);

}
.content-ten{
    margin-top:2em!important;
}
.content-name{
    margin-top:1em!important;
    margin-bottom:-0.25em!important;
    
}
p{
    color:white;
    text-align:center;
    font-size:1.25rem;
}
strong{
    color:white;
    font-size:1.5rem;
}
.content_editdate{
    text-align:left;
    font-size: 14px;
}
</style>
